name: My First Workflow

on:
  push:
    branches: [main]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "Hello from GitHub Actions!"
      - name: Print the date
        run: date
      - name: List files in this repo
        uses: actions/checkout@v4
      - run: ls -la
